---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  policyfile: test/fixtures/policies/default.rb

verifier:
  name: inspec

platforms:
  - name: centos-7.2
  - name: centos-6.7

suites:
  - name: default
    attributes:
      consul:
        config: &default-config
          owner: root
          group: consul
          ui: true
          bootstrap: true
          server: true
          datacenter: FortMeade
          encrypt: CGXC2NsXW4AvuB4h5ODYzQ==
          acl_master_token: doublesecret
          acl_datacenter: FortMeade
          acl_default_policy: deny
  - name: client
    named_run_list: client
    attributes:
      consul:
        config:
          server: false
          bootstrap_expect: 1
  - name: git
    attributes:
      go:
        version: 1.7
      consul:
        config: *default-config
        installation:
          provider: git
